add_newline = false

[battery]
disabled = true

[kubernetes]
symbol = "â˜¸ "
style = "red"
disabled = true

[cmd_duration]
disabled = true
min_time = 2

[directory]
truncation_length = 1
truncate_to_repo = false

[git_status]
conflicted = "ğŸ¤"
untracked = ""
stashed = ""
modified = "~"
staged = '[++$count](green)'
deleted = "--"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
format = '([$all_status$ahead_behind]($style) )'

[status]
style = "bg:blue"
symbol = "ğŸ’£ "
disabled = false

[ruby]
disabled = true

[java]
disabled= true

[nodejs]
disabled = true

[golang]
disabled = true

[python]
disabled = true

[terraform]
disabled = false
format = "ğŸª£ [$workspace]($style) ğŸª£ "

[gcloud]
disabled = true

[package]
disabled = true
